import Head from "next/head";
import Image from "next/image";
import { Ubuntu } from "next/font/google";
import MainPage from "@/container/Home";
import NewsPage from "./news-page";

const ubuntu = Ubuntu({ subsets: ["latin"], weight: ["300", "400", "700"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={ubuntu.className}>
        <MainPage />
      </main>
    </>
  );
}
